



WALLBOX_ANSWERS = { 
    "ANSWER_ERRAUTH" : "$ERR,AUTH", 
    "ANSWER_ERRBUSY" : "$ERR,BUSY", 
    "ANSWER_SYNTAX" : "$ERR,SYNTAX", 
    "ANSWER_AUTHFAIL" : "$BLE,AUTH,FAIL", 
    "ANSWER_AUTHOK" : "$BLE,AUTH,OK", 
    "ANSWER_WRITE_FAIL" : "$EEP,WRITE,FAIL", 
    "ANSWER_LOGOUT" : "$BLE,LOGOUT,OK" 
}

WALLBOX_BLE = { 
    "LOGIN" : "$BLE,AUTH;{pin}", 
    "LOGOUT" : "$BLE,LOGOUT" 
}

WALLBOX_COMMANDS = { 
    "START_CHARGE" : "$CMD,CHARGE,START,{delay}", 
    "STOP_CHARGE" : "$CMD,CHARGE,STOP,0" 
}


WALLBOX_EPROM = { 
    "INDEX_WRITE" : "$EEP,WRITE,IDX",
    "INDEX_READ" : "$EEP,READ,IDX",
    "READ_ALARMS" : "$EEP,READ,AL",
    "READ_MANUFACTURING" : "$EEP,READ,MF",
    "READ_SESSIONS" : "$EEP,READ,SL",
    "READ_SETTINGS" : "$EEP,READ,ST",
    "READ_APP_DATA" : "DATA,READ,AD",
    "READ_HW_SETTINGS" : "DATA,READ,HS",
    "READ_SUPPLY_VOLTAGE" : "DATA,READ,SV",

    "SET_USER_LIMIT" : "$EEP,WRITE,IDX,174,{limit}",
    "SET_DPM_LIMIT" : "$EEP,WRITE,IDX,158,{limit}",
    "SET_SAFE_LIMIT" : "$EEP,WRITE,IDX,156,{limit}",
    "SET_DPM_OFF" : "$EEP,WRITE,IDX,178,0",
    "SET_DPM_ON" : "$EEP,WRITE,IDX,178,1",

    "GET_USER_LIMIT" : "$EEP,READ,IDX,174",
    "GET_DPM_LIMIT" : "$EEP,READ,IDX,158",
    "GET_SAFE_LIMIT" : "$EEP,READ,IDX,156",
    "GET_DPM_STATUS" : "$EEP,READ,IDX,178"
}

